config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "restaurants#index"
  Rails.application.routes.draw do
    resources :restaurants do
      resources :reviews, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
  validates :name, presence: true
  validates :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant, presence: true
  validates :content, presence: true
  validates :rating, inclusion: { in: [0,1,2,3,4,5], allow_nil: false}, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
before_action :set_restaurant, only: [:show, :edit, :update]
  def index         # GET /restaurants
    @restaurants = Restaurant.all
  end

  def show          # GET /restaurants/:id
  end

  def new           # GET /restaurants/new
    @restaurant = Restaurant.new
  end

  def create        # POST /restaurants
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.valid?
      redirect_to restaurant_path(@restaurant)
    else
      render "restaurants/new"
    end
  end

  def edit          # GET /restaurants/:id/edit
  end

  def update        # PATCH /restaurants/:id
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy       # DELETE /restaurants/:id
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant
  def new
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.build(review_params)
    if @review.valid?
      @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
      <!-- Add these line for detecting device width -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :address %>:
  <%= f.text_field :address %><br />

  <%= f.label :phone_number %>:
  <%= f.text_field :phone_number %><br />

  <%= f.label :category %>:
  <%= f.text_field :category %><br />

  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form" %>
<%= link_to "Back to " + @restaurant.name, restaurants_path %>
<br>
<%= link_to "Back to Restaurants", restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<ul>
<% @restaurants.each do |restaurant| %>
<li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
<% end %>
</ul>
<%= link_to "Add restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= render "form" %>
<%= link_to "Back to Restaurants", restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.category %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.address %></p>
<ul>
  <% @restaurant.reviews.each do |review| %>
  <li>
    <%= review.rating %> <%= review.content %>
  </li>
  <% end %>
</ul>
<%= link_to "Add review", new_restaurant_review_path(@restaurant) %>
<br />
<%= link_to "Edit", edit_restaurant_path(@restaurant) %>
<br>
<%= link_to "Back to Restaurants", restaurants_path %>

app/views/reviews/_form.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :content %>:
  <%= f.text_field :content %><br />

  <%= f.label :rating %>:
  <%= f.text_field :rating %><br />

  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<%= render "form" %>
<%= link_to "Back to Restaurants", restaurants_path %>

app/views/reviews/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @review.rating %></p>
<p><%= @review.content %></p>
<%= link_to "Add review", new_restaurant_review_path(@restaurant) %>
<br />
<%= link_to "Edit", edit_review_path(@restaurant) %>
<br>
<%= link_to "Back to Restaurants", restaurants_path %>